const TEXT_INPUT = 'TEXT_INPUT'
const EMAIL_INPUT = 'EMAIL_INPUT'
const PHONE_INPUT = 'PHONE_INPUT'
const SHORT_TEXT = 'SHORT_TEXT'
const CHECKBOX = 'CHECKBOX'
const DATEPICKER = 'DATEPICKER'
const LONG_TEXT = 'LONG_TEXT'
const SELECT = 'SELECT'
const MULTISELECT = 'MULTISELECT'
const UPLOAD = 'UPLOAD'

export {
    TEXT_INPUT,
    EMAIL_INPUT,
    PHONE_INPUT,
    SHORT_TEXT,
    CHECKBOX,
    DATEPICKER,
    LONG_TEXT,
    SELECT,
    MULTISELECT,
    UPLOAD
}